import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {
  files = [
    {
      path: 'assets/portfolio/Canela-2022-MotaYCheetos-S.jpg',
      name: 'Mota & Cheetos',
      url: 'https://open.spotify.com/album/4pZSrWtCC3oZlGbpfBme4o?si=yxUuQRo0Tt2jqHntI85QRQ',
      band: 'Canela',
      year: '2022',
      type: 'Single',
      genre: 'garage-pop',
    },
    {
      path: 'assets/portfolio/Canela-2023-MeAtrapas-EP.jpg',
      name: 'Me Atrapas',
      url: 'https://open.spotify.com/album/3XVqNhXrCtlQ7iWkyMNcIP?si=OdQRKIS5SjuQmevDk7fs_Q',
      band: 'Canela',
      year: '2023',
      type: 'Single',
      genre: 'garage-pop',
    },
    {
      path: 'assets/portfolio/Canela-2023-Morres-LP.jpg',
      name: 'Morres',
      url: 'https://open.spotify.com/album/49YPl3HtqmYfP1trau8oHD?si=G_ATM6mPSLSbUheyovGwww',
      band: 'Canela',
      year: '2023',
      type: 'LP',
      genre: 'garage-pop',
    },
    {
      path: 'assets/portfolio/Canela-2023-Universidad-EP.jpg',
      name: 'Universidad',
      url: 'https://open.spotify.com/album/7uZZ5CPQywYzY16FpJDLOt?si=WwnyqrNiSdeUf6MK8l6y5w',
      band: 'Canela',
      year: '2023',
      type: 'EP',
      genre: 'garage-pop',
    },
    {
      path: 'assets/portfolio/Canela-2023-Volantes-EP.jpg',
      name: 'Volantes',
      url: 'https://open.spotify.com/album/6Lx8hAEmoibThQXv1AkodP?si=FtwJQOwfSsi1kurtFlWLYg',
      band: 'Canela',
      year: '2022',
      type: 'EP',
      genre: 'garage-pop',
    },
    {
      path: 'assets/portfolio/Cxtxrsis-2019-DelaSoledadAprendiTodoLoQueSe-S.jpg',
      name: 'De La Soledad Aprendí Todo Lo Que Sé',
      url: 'https://open.spotify.com/intl-es/album/5uPE2EjBlqj0RnZLA8cIZ8?si=J8r2y0c-RFOHdDw535Ue-A',
      band: 'Cxtxrsis',
      year: '2019',
      type: 'Single',
      genre: 'post-hardcore',
    },
    {
      path: 'assets/portfolio/Cxtxrsis-2019-SemillasDePensamientoRojo-EP.jpg',
      name: 'Semillas De Pensamiento Rojo',
      url: 'https://open.spotify.com/intl-es/album/2bUQXmC4OMooAiOSl7PcR8?si=O_CsXM1JRKigDcSBHbyPxA',
      band: 'Cxtxrsis',
      year: '2019',
      type: 'Single',
      genre: 'post-hardcore',
    },
    {
      path: 'assets/portfolio/EscalaCero-2017-Silencio-EP.jpg',
      name: 'Silencio',
      url: 'https://open.spotify.com/album/5gKBMpt6VpTMIou7QZAlrQ?si=alAWrY2JTsGopazUkbS6OA',
      band: 'Escala Cero',
      year: '2017',
      type: 'EP',
      genre: 'indie-rock',
    },
    {
      path: 'assets/portfolio/EscalaCero-2018-Adios-S.jpg',
      name: 'Adiós',
      url: 'https://open.spotify.com/album/7cLAruZG5RKkZo6wDzjuNb?si=8ZT0G3bwTAW80e-Sv3UjIg',
      band: 'Escala Cero',
      year: '2018',
      type: 'Single',
      genre: 'indie-rock',
    },
    {
      path: 'assets/portfolio/EscalaCero-2018-Volver-S.jpg',
      name: 'Volver',
      url: 'https://open.spotify.com/album/0WqTvRcczpzqXYGrVi3FJG?si=7qEfjq-KSVGoocvb8Fcauw',
      band: 'Escala Cero',
      year: '2018',
      type: 'Single',
      genre: 'indie-rock',
    },
    {
      path: 'assets/portfolio/EscalaCero-2024-OhNo-S.jpg',
      name: 'Oh No',
      url: 'https://open.spotify.com/album/2ZmC3FFAyZ0CN5rbXx8UPD?si=2kAXmITtQOKcBLrJJKiyaA',
      band: 'Escala Cero',
      year: '2024',
      type: 'Single',
      genre: 'indie-rock',
    },
    {
      path: 'assets/portfolio/Gratis-2024-FloresDeBach-S.jpg',
      name: 'Flores De Bach',
      url: 'https://open.spotify.com/intl-es/album/6KbYNwKBkL7TQRW2iJ0LjZ?si=1n5LeTdOQRqPfaosQsU--A',
      band: 'Gratis',
      year: '2024',
      type: 'Single',
      genre: 'garage-rock',
    },
    {
      path: 'assets/portfolio/GuestHouse-2021-ByMyself-S.jpg',
      name: 'By Myself',
      url: 'https://open.spotify.com/album/6qujFfWQnjL5WvzUjuQBzo?si=MFJSIP_KQqyVZ5wCg9C1gg',
      band: 'Guest House',
      year: '2021',
      type: 'Single',
      genre: 'grunge-gaze',
    },
    {
      path: 'assets/portfolio/GuestHouse-2021-GlassCannon97-S.jpg',
      name: "Glass Cannon '97",
      url: 'https://open.spotify.com/album/7BcElrFgCJiE9eDL2KJLQp?si=u59jLZR2QJ-hv3yjOVSyYg',
      band: 'Guest House',
      year: '2021',
      type: 'Single',
      genre: 'grunge-gaze',
    },
    {
      path: 'assets/portfolio/GuestHouse-2021-OldSongsJoySeemssoFarAway-EP.jpg',
      name: 'Old Songs / Joy Seems So Far Away',
      url: 'https://open.spotify.com/album/5ZwdpxYowrVVIRdslninIR?si=y17gbJKwSV6A-R5Mk6YFtQ',
      band: 'Guest House',
      year: '2021',
      type: 'EP',
      genre: 'emo',
    },
    {
      path: 'assets/portfolio/GuestHouse-2022-IShallBeNothing-EP.jpg',
      name: 'I Shall Be Nothing',
      url: 'https://open.spotify.com/album/3WjcJIGHh4bTHARfjHgGob?si=si6hIqBSQ8CYWA2X13edWA',
      band: 'Guest House',
      year: '2022',
      type: 'EP',
      genre: 'grunge-gaze',
    },
    {
      path: 'assets/portfolio/GuestHouse-2022-NewSelf-EP.jpg',
      name: 'New Self',
      url: 'https://open.spotify.com/album/3vme5SXMf1bedbpehDTqLw?si=_ArUEzXjRw2XRRiBoKe8pg',
      band: 'Guest House',
      year: '2021',
      type: 'EP',
      genre: 'grunge-gaze',
    },
    {
      path: 'assets/portfolio/GuestHouse-2022-OneDay-S.jpg',
      name: 'One Day',
      url: 'https://open.spotify.com/album/2Le93AwnjUHguhaqSxc0Zf?si=i7c8bbhRQmW-6fTnvOpwUQ',
      band: 'Guest House',
      year: '2021',
      type: 'Single',
      genre: 'grunge-gaze',
    },
    {
      path: 'assets/portfolio/GuestHouse-2023-NoLongerHuman-LP.jpg',
      name: 'No Longer Human',
      url: 'https://open.spotify.com/album/0cq72FadOuicroE8cgL72R?si=PtPo5Z35RlCBRN7bzpQjiw',
      band: 'Guest House',
      year: '2023',
      type: 'LP',
      genre: 'grunge-gaze',
    },
    {
      path: 'assets/portfolio/GuestHouse-2024-BoredReconnect-S.jpg',
      name: 'Bored / Reconnect',
      url: 'https://open.spotify.com/album/79SWHlhvTQMD4pkdM2nrBf?si=x_CC-XccQEa7Z2ltiSGTow',
      band: 'Guest House',
      year: '2024',
      type: 'Single',
      genre: 'nu-metal / grunge',
    },
    {
      path: 'assets/portfolio/HolySunn-2019-Beyond-EP.jpg',
      name: 'Beyond',
      url: 'https://open.spotify.com/intl-es/album/0rtZKlb2tCod3eGWLsBNXJ?si=9GVNjpV-T5uxW0_6RwPrKQ',
      band: 'Holy Sunn',
      year: '2019',
      type: 'EP',
      genre: 'psych-rock',
    },
    {
      path: 'assets/portfolio/Honeybliss-2021-YaNo-S.jpg',
      name: 'Ya No',
      url: 'https://open.spotify.com/album/4e92ytuuHOHyPXRJcYM7vE?si=JUlRf1jSQ96zN_nvL1lxSw',
      band: 'Honeybliss',
      year: '2021',
      type: 'Single',
      genre: 'pop',
    },
    {
      path: 'assets/portfolio/Honeybliss-2022-Cuento-S.jpg',
      name: 'Cuento',
      url: 'https://open.spotify.com/album/2KBKnZfVuhVhsCU7V59aCF?si=w_QFCO4UTSC6HKDyf1_OLw',
      band: 'Honeybliss',
      year: '2022',
      type: 'Single',
      genre: 'pop',
    },
    {
      path: 'assets/portfolio/Honeybliss-2022-DeBlancoenunKiosko-S.jpg',
      name: 'De Blanco En Un Kiosko',
      url: 'https://open.spotify.com/album/4Xdvy772u7RbothopmkSdG?si=xhGD2ZXXTz-GqtSQZ14nbQ',
      band: 'Honeybliss',
      year: '2022',
      type: 'Single',
      genre: 'pop',
    },
    {
      path: 'assets/portfolio/Honeybliss-2022-SushiDate-S.jpg',
      name: 'Sushi Date',
      url: 'https://open.spotify.com/album/1QshR1cvbUsNzNNY5vNyxL?si=CWITwT8MR1CFCerxajWdzw',
      band: 'Honeybliss',
      year: '2022',
      type: 'Single',
      genre: 'pop',
    },
    {
      path: 'assets/portfolio/Hornets-2023-DontFreakOut-S.jpg',
      name: "Don't Freak Out",
      url: 'https://open.spotify.com/intl-es/album/4uDYE0B8MLO16saub1z9vd?si=ldy1hpX8Q-qMTW9z6i-khw',
      band: 'Hornets!',
      year: '2023',
      type: 'Single',
      genre: 'indie-rock',
    },
    {
      path: 'assets/portfolio/LigaJuvenil-2024-Frio-S.jpg',
      name: 'Frío',
      url: 'https://open.spotify.com/intl-es/album/2kx6LxPPVNTIkzRPELIYkA?si=SBhe8gEyTNiPu0Xf-7waIw',
      band: 'Liga Juvenil',
      year: '2024',
      type: 'Single',
      genre: 'dreampop',
    },
    {
      path: 'assets/portfolio/LVelazquez-2023-Elefante-S.jpg',
      name: 'Elefante',
      url: 'https://open.spotify.com/intl-es/album/2T7MkiCxVeYdEXnV51h427?si=AtSIZMp5QiWaJUIe1hNXCQ',
      band: 'L Velázquez',
      year: '2023',
      type: 'Single',
      genre: 'alt-rock',
    },
    {
      path: 'assets/portfolio/LVelazquez-2024-Atomos-S.jpg',
      name: 'Átomos',
      url: 'https://open.spotify.com/intl-es/album/4bSwWkToUtjnHCUHa1SmMK?si=MFQwhMEAToCNoExxu2bJxQ',
      band: 'L Velázquez',
      year: '2024',
      type: 'Single',
      genre: 'alt-rock',
    },
    {
      path: 'assets/portfolio/Nolee-2023-Vampirita-S.jpg',
      name: 'Vampirita',
      url: 'https://open.spotify.com/intl-es/album/4ryUDRIvSXu1yGPkiVM4lO?si=OoclKdqKQ9Wuob37stGolw',
      band: 'Nolee',
      year: '2023',
      type: 'Single',
      genre: 'neoperreo',
    },
    {
      path: 'assets/portfolio/SpaceAtlas-2018-BrandNewAir-S.jpg',
      name: 'Brand New Air',
      url: 'https://open.spotify.com/album/29mSe4kG9HviDcaaWdKUVk?si=3V0lxp8uSia6E3a8Dhrj7Q',
      band: 'Space Atlas',
      year: '2018',
      type: 'Single',
      genre: 'post-rock',
    },
    {
      path: 'assets/portfolio/SpaceAtlas-2019-SomewhereBetweenDarkAndLight-S.jpg',
      name: 'Somewhere Between Dark And Light',
      url: 'https://open.spotify.com/album/3QlJWjKszXS38nElUR9XsD?si=gs6LDPvRS9qBWWWOLRS_eQ',
      band: 'Space Atlas',
      year: '2019',
      type: 'Single',
      genre: 'post-rock',
    },
    {
      path: 'assets/portfolio/SpaceAtlas-2020-FirstMoon.jpg',
      name: 'First Moon',
      url: 'https://open.spotify.com/album/3bWSUvqnMEEmkgh2buFLHE?si=PylVfriPSI-vLcgcYvMGmQ',
      band: 'Space Atlas',
      year: '2020',
      type: 'Single',
      genre: 'post-rock',
    },
    {
      path: 'assets/portfolio/Yayfog-2019-CrossedOutEyes-S.jpg',
      name: 'Crossed Out Eyes',
      url: 'https://open.spotify.com/album/2QfjdgTXY4X5HuuB8MDeBT?si=aFwYfH0gSJKSMj3rgacVjg',
      band: 'Yayfog',
      year: '2019',
      type: 'Single',
      genre: 'emo',
    },
    {
      path: 'assets/portfolio/Yayfog-2019-TheSunOldToy-S.jpg',
      name: 'The Sun / Old Toy',
      url: 'https://open.spotify.com/album/7oBzgjptcqc1015EFMD5IR?si=DGHrVf7uS065JznAPnhTAw',
      band: 'Yayfog',
      year: '2019',
      type: 'Single',
      genre: 'emo',
    },
    {
      path: 'assets/portfolio/Yayfog-2020-Empty-EP.jpg',
      name: 'Empty',
      url: 'https://open.spotify.com/album/1N1I0DowPB0BNlgxujsYRW?si=S3w3tRNxSs2aedUivaU5vA',
      band: 'Yayfog',
      year: '2020',
      type: 'Single',
      genre: 'emo',
    },
  ];

  ngOnInit(): void {
    this.files.sort(() => Math.random() - 0.5);
  }
}
